import React from 'react';
import {
  GLOBAL_AVG,
  GOAL_2030,
  CATEGORY_LABELS,
  getEcoScore,
  getRank,
} from '../utils/calculations';

function Reports({ state }) {
  const fp = state.footprint;
  const goalKg = state.profile?.goalKg ?? GOAL_2030;
  const hasData = fp.total > 0;
  const yearlyProjection = hasData ? (fp.total * 12).toFixed(1) : '—';
  const score = getEcoScore(fp.total);
  const rank = getRank(score);
  const displayName = state.profile?.name?.trim() || 'Eco Guardian';
  const reportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const vsGlobal = hasData ? ((fp.total / GLOBAL_AVG) * 100).toFixed(0) : '—';
  const vsGoal = hasData ? ((fp.total / goalKg) * 100).toFixed(0) : '—';

  if (!hasData) {
    return (
      <div className="p-6 md:p-10 max-w-4xl mx-auto text-center">
        <div className="app-glass-card-dark p-12">
          <div className="text-5xl mb-4">📄</div>
          <h2 className="app-section-title mb-2">No report available</h2>
          <p className="app-section-sub">Complete a footprint calculation to generate your monthly report.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 md:p-10 max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 no-print">
        <div>
          <h2 className="app-section-title">Monthly Report</h2>
          <p className="app-section-sub">Summary for {reportDate}</p>
        </div>
        <button type="button" onClick={() => window.print()} className="app-btn-primary">
          <i className="fa-solid fa-print mr-2" /> Print report
        </button>
      </div>

      <div className="print-report app-glass-card-dark p-8 md:p-10 space-y-8">
        <div className="border-b border-white/10 pb-6">
          <h1 className="text-2xl font-black">EcoAura Carbon Footprint Report</h1>
          <p className="text-white/50 text-sm mt-1">{displayName} · {reportDate}</p>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="p-4 rounded-xl bg-white/5">
            <div className="text-xs text-white/40 uppercase tracking-wider">Monthly total</div>
            <div className="text-2xl font-black text-emerald-400">{fp.total} kg</div>
          </div>
          <div className="p-4 rounded-xl bg-white/5">
            <div className="text-xs text-white/40 uppercase tracking-wider">Yearly projection</div>
            <div className="text-2xl font-black">{yearlyProjection} kg</div>
          </div>
          <div className="p-4 rounded-xl bg-white/5">
            <div className="text-xs text-white/40 uppercase tracking-wider">Eco score</div>
            <div className="text-2xl font-black">{score}</div>
          </div>
          <div className="p-4 rounded-xl bg-white/5">
            <div className="text-xs text-white/40 uppercase tracking-wider">Rank</div>
            <div className="text-lg font-bold text-emerald-300">{rank}</div>
          </div>
        </div>

        <div>
          <h3 className="font-bold mb-4">Category breakdown</h3>
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/10 text-white/50">
                <th className="py-2 text-left">Category</th>
                <th className="py-2 text-right">kg CO₂/month</th>
                <th className="py-2 text-right">% of total</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(CATEGORY_LABELS).map(([key, label]) => (
                <tr key={key} className="border-b border-white/5">
                  <td className="py-3">{label}</td>
                  <td className="py-3 text-right font-semibold">{fp[key]}</td>
                  <td className="py-3 text-right text-white/50">
                    {fp.total ? Math.round((fp[key] / fp.total) * 100) : 0}%
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="grid md:grid-cols-2 gap-4">
          <div className="p-4 rounded-xl bg-white/5">
            <div className="text-xs text-white/40 mb-1">vs global average ({GLOBAL_AVG} kg)</div>
            <div className="font-bold">{vsGlobal}% of global avg</div>
          </div>
          <div className="p-4 rounded-xl bg-white/5">
            <div className="text-xs text-white/40 mb-1">vs your goal ({goalKg} kg)</div>
            <div className="font-bold">{vsGoal}% of goal</div>
          </div>
        </div>

        <p className="text-xs text-white/30 pt-4 border-t border-white/10">
          Generated by EcoAura Carbon Footprint Tracker. Estimates use standard emission factors for educational purposes.
        </p>
      </div>
    </div>
  );
}

export default Reports;
